---
# Debian OS
- name: Neccessary operations for Sonarqube on  Debian OS
  include_tasks: req.yml
  when: ansible_os_family == 'Debian'

- include_tasks: postgresql.yml
  when: ansible_os_family == 'Debian'

- include_tasks: python.yml
  when: ansible_os_family == 'Debian'

- include_tasks: sonarqube-setup.yml.yml
  when: ansible_os_family == 'Debian'


