---
# Moved this here because if jenkins signing key becomes outdated, it affects the apt package update
- name: download jenkins, terraform & kubernetes keys
  apt_key: 
   url: "{{ item }}"
   state: present
  loop:
    - https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    - https://apt.releases.hashicorp.com/gpg

- name: add jenkins, kubernetes, terraform repositories
  apt_repository: 
   repo: "{{ item }}"
   state: present
  loop:
    - "deb https://pkg.jenkins.io/debian-stable binary/"
    - "deb https://apt.releases.hashicorp.com/ focal  main"



# Install and Configure these softwares on CI server for Containerization in Pipeline
- name: install java 17 and other packages
  ansible.builtin.apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
  loop: 
    - fontconfig
    - openjdk-17-jre
    - jq
    - docker.io
    - unzip
    - docker-compose

- name: Update ubuntu
  ansible.builtin.apt:
   update_cache: yes

- name: install the following packages using apt_get
  ansible.builtin.apt: 
   name: "{{ item }}"
   state: present
   update_cache: yes
   force_apt_get: yes
  loop:
    - jenkins
    - curl
    - zip
    - ca-certificates
    - apt-transport-https


- name: start and enable jenkins
  ansible.builtin.service:
   name: jenkins
   state: started
   enabled: true
   daemon_reload: yes
  notify: Restart jenkins server

# - name: install python3 packages
#   ansible.builtin.apt:
#     name: 
#       - python3
#       - python3-pip
#       - python3-dev
#       - libpq-dev
#     update_cache: true
#     state: present

# - name: Install setuptools
#   pip:
#     name: setuptools
#     extra_args: --upgrade

# - name: upgrade pip command
#   pip:
#     name: pip
#     extra_args: --upgrade


# - name: install boto3 & botocore
#   pip:
#     name:  
#       - botocore
#       - boto3
#     executable: pip3
