## Install NVM & Setup Node
- name: Setup Node
  become_flags: -i # Execute config files such as .profile (Ansible uses non-interactive login shells)
  block:
    - name: Install node version manager
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

    - name: Setup .profile
      lineinfile:
        path: $HOME/.profile
        line: source $HOME/.nvm/nvm.sh # This will make sure Node is on the user's PATH
        create: yes
    
    - name: Install node
      shell: |
       source $HOME/.nvm/nvm.sh && nvm install {{item}}
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/node/v{{item}}"
      loop:
        - 18.17.0

    - name: Set preferred node version to be default
      shell: |
        source $HOME/.nvm/nvm.sh && nvm use 18.17.0 && nvm alias default 18.17.0
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/alias/default"



    # ### INSTALL NODEJS USING APT TOO

- name: download nodejs keys
  apt_key: 
   url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
   state: present


- name: add nodejs apt repositories
  apt_repository: 
   repo: "deb https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"
   state: present

- name: Update ubuntu
  ansible.builtin.apt:
   update_cache: yes

- name: install nodejs
  ansible.builtin.apt: 
   name: nodejs
   state: present
   update_cache: yes

- name: Set default Node.js version
  command: sudo update-alternatives --install /usr/bin/node node /usr/bin/nodejs 18
  ignore_errors: true

- name: Verify Node.js version
  command: node --version
  register: node_version

- name: Display Node.js version
  debug:
    var: node_version.stdout_lines