---
grype_debian_url: https://github.com/anchore/grype/releases/download/v0.46.0/grype_0.46.0_linux_amd64.deb

github_repositories:
 - {url: https://github.com/cncgrbteam/fms-frontend.git, dest: $HOME}

 
 - {url: https://github.com/cncgrbteam/fms-auth-user-management.git, dest: $HOME}


 - {url: https://github.com/cncgrbteam/fms-api-gateway.git, dest: $HOME}


 - {url: https://github.com/cncgrbteam/fms-notification-service.git, dest: $HOME} 

 
 - {url: https://github.com/cncgrbteam/fms-vehicle-service.git, dest: $HOME}


 - {url: https://github.com/cncgrbteam/fms-payment-service.git, dest: $HOME}  


 - {url: https://github.com/cncgrbteam/fms-concept-nova-admin.git, dest: $HOME}  