plugin: aws_ec2
# aws_profile: default
# aws_access_key: "check for aws access key. Removed for security purpose"
# aws_secret_key: "check for aws secret key. Removed for security purpose"

regions:
  - "us-east-1"

strict: False

keyed_groups:
- key: tags
  prefix: tag

filters:
  tag:Name:
    - ACS-bastion
    - ACS-app-server
    - ACS-nginx

  instance-state-name : running
  
hostnames:
# a list in order of precedence for hostname variables.
  - ip-address
  - tag:Name
  - private-ip-address
  - dns-name
  

compose:
  ansible_host: private_ip_address

