- name: install nfs client
  ansible.builtin.apt: 
   name: nfs-common
   state: present
   update_cache: yes

- name: Ensure rpcbind is running
  service:
    name: rpcbind
    state: started
    enabled: yes

- name: Wait for the NFS server to become reachable
  wait_for:
    timeout: 300
    host: "{{ nfs_server }}"
    port: 2049

- name: Mount NFS volume
  mount:
    src: "{{ nfs_server }}:{{ path_export }}"
    path: "{{ client_shared_dir }}"
    opts: defaults
    boot: true
    state: mounted
    fstype: nfs